### ISSUE TITLE
invalid syntax on connections.py

### ISSUE THREAD

**Issue by pgodwin** [jacobm001/dbt-mssql#16]
Running `dbt debug` results in an invalid syntax error in  File "/usr/local/lib/python2.7/dist-packages/dbt/adapters/mssql/connections.py", line 139. See the debug output below.

I'm guessing I've missed something really simple - any ideas?

### ~/.dbt/profiles.yml:
```yaml
my-mssql-db:
  target: dev
  outputs:
    dev:
      type: mssql
      driver: 'ODBC Driver 17 for SQL Server'
      host: sql01.local
      database: dbt_test
      schema: dbo
      username: dbt_user
      password: ******
```

### Environment
```bash
$ python --version
Python 2.7.15+

$ pip list | grep dbt-mssql
dbt-mssql (1.0.7)

$  dbt --version
installed version: 0.14.3
   latest version: 0.14.3

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

```
### Debug Output

```bash
$ dbt -d debug
Running with dbt=0.14.3
2019-10-21 16:03:27,649 (MainThread): Tracking: tracking
2019-10-21 16:03:27,654 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa097e2f3d0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa097e2f750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa09b391bd0>], 'label': 'start'}
dbt version: 0.14.3
python version: 2.7.15+
python path: /usr/bin/python
os info: Linux-4.15.0-46-generic-x86_64-with-Ubuntu-18.04-bionic
Using profiles.yml file at /***/.dbt/profiles.yml

2019-10-21 16:03:28,781 (MainThread): Sending event: {'category': 'dbt', 'action': 'invocation', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa09613b850>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa09613b050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa09613b410>], 'label': 'end'}
2019-10-21 16:03:29,741 (MainThread): Flushing usage events
2019-10-21 16:03:29,741 (MainThread): Encountered an error:
2019-10-21 16:03:29,741 (MainThread): invalid syntax (connections.py, line 139)
2019-10-21 16:03:29,744 (MainThread): Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dbt/main.py", line 82, in main
    results, succeeded = handle_and_check(args)
  File "/usr/local/lib/python2.7/dist-packages/dbt/main.py", line 151, in handle_and_check
    task, res = run_from_args(parsed)
  File "/usr/local/lib/python2.7/dist-packages/dbt/main.py", line 216, in run_from_args
    results = task.run()
  File "/usr/local/lib/python2.7/dist-packages/dbt/task/debug.py", line 108, in run
    self.test_configuration()
  File "/usr/local/lib/python2.7/dist-packages/dbt/task/debug.py", line 234, in test_configuration
    profile_status = self._load_profile()
  File "/usr/local/lib/python2.7/dist-packages/dbt/task/debug.py", line 212, in _load_profile
    self.profile = Profile.from_args(self.args, self.profile_name)
  File "/usr/local/lib/python2.7/dist-packages/dbt/config/profile.py", line 381, in from_args
    threads_override=threads_override
  File "/usr/local/lib/python2.7/dist-packages/dbt/config/profile.py", line 350, in from_raw_profiles
    threads_override=threads_override,
  File "/usr/local/lib/python2.7/dist-packages/dbt/config/profile.py", line 304, in from_raw_profile_info
    profile_data, profile_name, target_name
  File "/usr/local/lib/python2.7/dist-packages/dbt/config/profile.py", line 172, in _credentials_from_profile
    cls = load_plugin(typename)
  File "/usr/local/lib/python2.7/dist-packages/dbt/adapters/factory.py", line 32, in load_plugin
    mod = import_module('.' + adapter_name, 'dbt.adapters')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/dbt/adapters/mssql/__init__.py", line 1, in <module>
    from dbt.adapters.mssql.connections import MSSQLConnectionManager
  File "/usr/local/lib/python2.7/dist-packages/dbt/adapters/mssql/connections.py", line 139
    con_str.append(f"DRIVER={{{credentials.driver}}}")
                                                    ^
SyntaxError: invalid syntax

2019-10-21 16:03:29,747 (MainThread): DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020.
Please upgrade your Python as Python 2.7 won't be maintained after that date.
A future version of dbt will drop support for Python 2.7.

**Comment by pgodwin** [comment]
Okay easy fixed. It needs Python 3.6 and I somehow missed it in the dbt documentation (actually on the Ubuntu and Centos instructions it doesn't mention this at all but does on other pages).
